import glob as gb
import os
import warnings
import pandas as pd
import xlwings as xw 
import re
import streamlit as st
import tempfile
from src import ps_e

# Filter out warning messages generated by modules or functions called in code.
warnings.filterwarnings("ignore")

def get_PSE_report(name):
    try:
        with open(name) as f:
            flist = f.readlines()
    
            pse_count = [] 
            for num, line in enumerate(flist, 0):
                if 'PS-E' in line:
                    pse_count.append(num)
                if 'PS-F' in line:
                    numend = num
            numstart = pse_count[0] 
            pse_rpt = flist[numstart:numend]
            
            pse_str = []
            pse_type = []
            # Iterate through each line in lvb_rpt
            for line in pse_rpt:
                line = re.sub(r'(\d)\.(\d+)\.', r'\1. \2.', line)
                # Check conditions and append lines containing relevant data to lvb_str list
                if (('.' in line and 'KW' in line) or ('JAN' in line or 'FEB' in line or 'MAR' in line
                      or 'JUN' in line or 'APR' in line or 'MAY' in line or 'JUN' in line or 'JUL' in line or 'AUG' in line or
                      'SEP' in line or 'OCT' in line or 'NOV' in line or 'DEC' in line) or
                    ('.' in line and 'MAX KW' in line)):
                    pse_str.append(line)
                elif ("PS-E" in line and "WEATHER" in line):
                    pse_type.append(line)
            
            # result list to store filtered columns. after 10th column from last remaining values in 1 column.
            result = []  
            for line in pse_str:
                lvb_list = []
                # Split the line by whitespace and store the result in splitter
                splitter = line.split()
                # Join the first part of the splitter except the last 10 elements and store it as space_name
                space_name = " ".join(splitter[:-13])
                # Add space_name as the first element of lvb_list
                lvb_list=splitter[-13:]
                lvb_list.insert(0,space_name)
                # Append lvb_list to result
                result.append(lvb_list)
                
            # strore list to dataframe
            pse_df = pd.DataFrame(result) 
            # # Allot lvb_df columns from sim file
            pse_df.columns = ['UNIT', 'LIGHTS', 'TASK_LIGHTS', 'MISC_EQUIP', 'SPACE_HEATING', 
                                 'SPACE_COOLING', 'HEAT_REJECT', 'PUMPS & AUX', 'VENT FANS', 'REFRIG DISPLAY',
                                 'HT PUMP SUPPLEM', 'DOMEST HOT WTR', 'EXT USAGE', 'TOTAL']
            
            pse_df.index.name = name
            value_before_backslash = ''.join(reversed(name)).split("\\")[0]
            name1 = ''.join(reversed(value_before_backslash))
            name = name1.rsplit(".", 1)[0]
            # pse_df.insert(0, 'RUNNAME', name)
            # print(pse_df) 
    
            # Find the index of the first occurrence of "JAN" followed by "FEB"
            start_index = None
            for i in range(len(pse_df) - 1):
                if pse_df['LIGHTS'][i] == 'JAN' and pse_df['LIGHTS'][i+1] == 'FEB':
                    start_index = i
                    break
    
            # If "JAN" followed by "FEB" found, delete rows from "JAN" to the end
            if start_index is not None:
                pse_df = pse_df.iloc[0:start_index]
    
            ########################################################################
    
            for i in range(len(pse_df)):
                if i < len(pse_df) - 1 and ((pse_df['UNIT'][i] == 'MAX KW' and pse_df['LIGHTS'][i+1] == 'KWH') or (pse_df['UNIT'][i] == 'MAX KW' and pse_df['UNIT'][i+1] == 'KWH')):
                    new_row = {'UNIT': '', 'LIGHTS': 'TOTAL'}  # New row to be inserted
                    pse_df = pd.concat([pse_df.iloc[:i+1], pd.DataFrame([new_row]), pse_df.iloc[i+1:]]).reset_index(drop=True)
    
            # This will tell how many meters we have in KW and KWH case(in CSV)
            countMeters = 0
            for i in range(len(pse_df)):
                if pse_df['LIGHTS'][i] == 'JAN':
                    countMeters += 1
    
            values = []
            for item in pse_type:
                start_index = item.find("for") + len("for")
                end_index = item.find("WEATHER")
                value = item[start_index:end_index].strip()
                values.append(value)
            values1 = list(dict.fromkeys(values))
    
            values2 = []
            for i in range(countMeters):
                values2.append(values1[i])
            
            # Iterate over DataFrame indices
            j = 0
            for i in range(len(pse_df)):
                if pse_df['LIGHTS'].iloc[i] == 'JAN':
                    new_row = {'UNIT': values2[j]}
                    pse_df = pd.concat([pse_df.iloc[:i], pd.DataFrame([new_row]), pse_df.iloc[i:]]).reset_index(drop=True)
                    j += 1
                    if(j == countMeters):
                        break
    
            # Reset index after concatenation
            pse_df.reset_index(drop=True, inplace=True)
            pse_df = pse_df.tail(2).reset_index(drop=True)
            # st.write(pse_df)
    
        return pse_df
    except Exception as e:
        print(f"An error occurred: {e}")
        columns = ['AZIMUTH', 'AVERAGE(U-VALUE/WINDOWS)(BTU/HR-SQFT-F)', 'AVERAGE(U-VALUE/WALLS)(BTU/HR-SQFT-F)', 'AVERAGE U-VALUE(WALLS+WINDOWS)(BTU/HR-SQFT-F)', 
                              'WINDOW(AREA)(SQFT)', 'WALL(AREA)(SQFT)', 'WINDOW+WALL(AREA)(SQFT)']
        return pd.DataFrame(columns=columns)

def get_END_USE(df, sim_files):
    end_use_map = {
        "Interior lighting": "LIGHTS",
        "Exterior lighting": "EXT USAGE",
        "Space heating": "SPACE_HEATING",
        "Space cooling": "SPACE_COOLING",
        "Pumps": "PUMPS & AUX",
        "Heat rejection": "HEAT_REJECT",
        "Fans - interior ventilation": "VENT FANS",
        "Service water heating": "DOMEST HOT WTR",
        "Receptacle equipment": ""
    }

    pse_dfs = []
    rotation_labels = [
        'Baseline 0° rotation',
        'Baseline 90° rotation',
        'Baseline 180° rotation',
        'Baseline 270° rotation',
    ]

    for i, sim_file in enumerate(sim_files):
        with tempfile.NamedTemporaryFile(delete=False, suffix=".sim") as temp_file:
            temp_file.write(sim_file.read())
            temp_file_path = temp_file.name
            
        pse_df = get_PSE_report(temp_file_path)

        pse_df_int_light_kwh = pse_df['LIGHTS'][0]
        pse_df_int_light_kw = pse_df['LIGHTS'][1]
        pse_df_ext_light_kwh = pse_df['EXT USAGE'][0]
        pse_df_ext_light_kw = pse_df['EXT USAGE'][1]
        pse_df_heat_kwh = pse_df['SPACE_HEATING'][0]
        pse_df_heat_kw = pse_df['SPACE_HEATING'][1]
        pse_df_cool_kwh = pse_df['SPACE_COOLING'][0]
        pse_df_cool_kw = pse_df['SPACE_COOLING'][1]
        pse_df_pumps_kwh = pse_df['PUMPS & AUX'][0]
        pse_df_pumps_kw = pse_df['PUMPS & AUX'][1]
        pse_df_heat_reject_kwh = pse_df['HEAT_REJECT'][0]
        pse_df_heat_reject_kw = pse_df['HEAT_REJECT'][1]
        pse_df_fans_kwh = pse_df['VENT FANS'][0]
        pse_df_fans_kw = pse_df['VENT FANS'][1]
        pse_df_wtr_kwh = pse_df['DOMEST HOT WTR'][0]
        pse_df_wtr_kw = pse_df['DOMEST HOT WTR'][1]
        pse_df_equip_kwh = pse_df['MISC_EQUIP'][0]
        pse_df_equip_kw = pse_df['MISC_EQUIP'][1]

        col = rotation_labels[i]
        df[col][0] = float(pse_df_int_light_kwh)
        df[col][1] = float(pse_df_int_light_kw)
        df[col][2] = float(pse_df_ext_light_kwh)
        df[col][3] = float(pse_df_ext_light_kw)
        df[col][4] = float(pse_df_heat_kwh)
        df[col][5] = float(pse_df_heat_kw)
        df[col][6] = float(pse_df_cool_kwh)
        df[col][7] = float(pse_df_cool_kw)
        df[col][8] = float(pse_df_pumps_kwh)
        df[col][9] = float(pse_df_pumps_kw)
        df[col][10] = float(pse_df_heat_reject_kwh)
        df[col][11] = float(pse_df_heat_reject_kw)
        df[col][12] = float(pse_df_fans_kwh)
        df[col][13] = float(pse_df_fans_kw)
        df[col][16] = float(pse_df_wtr_kwh)
        df[col][17] = float(pse_df_wtr_kw)
        df[col][18] = float(pse_df_equip_kwh)
        df[col][19] = float(pse_df_equip_kw)

    cols = [
        'Baseline 0° rotation',
        'Baseline 90° rotation',
        'Baseline 180° rotation',
        'Baseline 270° rotation'
    ]
    df = df.iloc[:, :-4]
    # df = df.iloc[:, :-1]
    # df = df.drop(df.columns[1], axis=1)
    df[cols] = df[cols].apply(pd.to_numeric, errors='coerce')
    total_0_degree = df['Baseline 0° rotation'].sum()
    total_90_degree = df['Baseline 90° rotation'].sum()
    total_180_degree = df['Baseline 180° rotation'].sum()
    total_270_degree = df['Baseline 270° rotation'].sum()
    df['Baseline 0° rotation'][49] = total_0_degree
    df['Baseline 90° rotation'][49] = total_90_degree
    df['Baseline 180° rotation'][49] = total_180_degree
    df['Baseline 270° rotation'][49] = total_270_degree
    df['Baseline 0° rotation'][50] = 0
    df['Baseline 90° rotation'][50] = 0
    df['Baseline 180° rotation'][50] = 0
    df['Baseline 270° rotation'][50] = 0
    df['Baseline 0° rotation'][51] = 0
    df['Baseline 90° rotation'][51] = 0
    df['Baseline 180° rotation'][51] = 0
    df['Baseline 270° rotation'][51] = 0
    df['Baseline Design Total (Average of 4 rotations)'] = df[cols].sum(axis=1) / 4

    st.success("Files processed and CSV updated successfully!")
    st.dataframe(df)

    st.download_button(
        label="Download Modified CSV",
        data=df.to_csv(index=False),
        file_name="modified_output.csv",
        mime="text/csv"
    ) 

def get_END_USE_Proposed(df, sim_files):
    end_use_map = {
        "Interior lighting": "LIGHTS",
        "Exterior lighting": "EXT USAGE",
        "Space heating": "SPACE_HEATING",
        "Space cooling": "SPACE_COOLING",
        "Pumps": "PUMPS & AUX",
        "Heat rejection": "HEAT_REJECT",
        "Fans - interior ventilation": "VENT FANS",
        "Service water heating": "DOMEST HOT WTR",
        "Receptacle equipment": ""
    }

    pse_dfs = []
    rotation_labels = [
        'Baseline 0° rotation',
        'Baseline 90° rotation',
        'Baseline 180° rotation',
        'Baseline 270° rotation',
        'Proposed'
    ]

    for i, sim_file in enumerate(sim_files):
        with tempfile.NamedTemporaryFile(delete=False, suffix=".sim") as temp_file:
            temp_file.write(sim_file.read())
            temp_file_path = temp_file.name
            
        pse_df = get_PSE_report(temp_file_path)
        # st.write(pse_df)
        pse_df_int_light_kwh = pse_df['LIGHTS'][0]
        pse_df_int_light_kw = pse_df['LIGHTS'][1]
        pse_df_ext_light_kwh = pse_df['EXT USAGE'][0]
        pse_df_ext_light_kw = pse_df['EXT USAGE'][1]
        pse_df_heat_kwh = pse_df['SPACE_HEATING'][0]
        pse_df_heat_kw = pse_df['SPACE_HEATING'][1]
        pse_df_cool_kwh = pse_df['SPACE_COOLING'][0]
        pse_df_cool_kw = pse_df['SPACE_COOLING'][1]
        pse_df_pumps_kwh = pse_df['PUMPS & AUX'][0]
        pse_df_pumps_kw = pse_df['PUMPS & AUX'][1]
        pse_df_heat_reject_kwh = pse_df['HEAT_REJECT'][0]
        pse_df_heat_reject_kw = pse_df['HEAT_REJECT'][1]
        pse_df_fans_kwh = pse_df['VENT FANS'][0]
        pse_df_fans_kw = pse_df['VENT FANS'][1]
        pse_df_wtr_kwh = pse_df['DOMEST HOT WTR'][0]
        pse_df_wtr_kw = pse_df['DOMEST HOT WTR'][1]
        pse_df_equip_kwh = pse_df['MISC_EQUIP'][0]
        pse_df_equip_kw = pse_df['MISC_EQUIP'][1]

        col = rotation_labels[i]
        df[col][0] = float(pse_df_int_light_kwh)
        df[col][1] = float(pse_df_int_light_kw)
        df[col][2] = float(pse_df_ext_light_kwh)
        df[col][3] = float(pse_df_ext_light_kw)
        df[col][4] = float(pse_df_heat_kwh)
        df[col][5] = float(pse_df_heat_kw)
        df[col][6] = float(pse_df_cool_kwh)
        df[col][7] = float(pse_df_cool_kw)
        df[col][8] = float(pse_df_pumps_kwh)
        df[col][9] = float(pse_df_pumps_kw)
        df[col][10] = float(pse_df_heat_reject_kwh)
        df[col][11] = float(pse_df_heat_reject_kw)
        df[col][12] = float(pse_df_fans_kwh)
        df[col][13] = float(pse_df_fans_kw)
        df[col][16] = float(pse_df_wtr_kwh)
        df[col][17] = float(pse_df_wtr_kw)
        df[col][18] = float(pse_df_equip_kwh)
        df[col][19] = float(pse_df_equip_kw)

    cols = [
        'Baseline 0° rotation',
        'Baseline 90° rotation',
        'Baseline 180° rotation',
        'Baseline 270° rotation',
        'Proposed'
    ]
    # df = df.iloc[:, :-4]
    df = df.iloc[:, :-2]
    # df = df.iloc[:, :-3]
    df = df.drop(df.columns[1], axis=1)
    df[cols] = df[cols].apply(pd.to_numeric, errors='coerce')
    total_0_degree = df['Baseline 0° rotation'].sum()
    total_90_degree = df['Baseline 90° rotation'].sum()
    total_180_degree = df['Baseline 180° rotation'].sum()
    total_270_degree = df['Baseline 270° rotation'].sum()
    df['Baseline 0° rotation'][49] = total_0_degree
    df['Baseline 90° rotation'][49] = total_90_degree
    df['Baseline 180° rotation'][49] = total_180_degree
    df['Baseline 270° rotation'][49] = total_270_degree
    df['Baseline 0° rotation'][50] = 0
    df['Baseline 90° rotation'][50] = 0
    df['Baseline 180° rotation'][50] = 0
    df['Baseline 270° rotation'][50] = 0
    df['Baseline 0° rotation'][51] = 0
    df['Baseline 90° rotation'][51] = 0
    df['Baseline 180° rotation'][51] = 0
    df['Baseline 270° rotation'][51] = 0

    st.success("Files processed and CSV updated successfully!")
    st.dataframe(df)

    st.download_button(
        label="Download Modified CSV",
        data=df.to_csv(index=False),
        file_name="modified_output.csv",
        mime="text/csv"
    ) 
